<a href="https://colab.research.google.com/github/123franklin321/meu_primeiro_codigo.py/blob/master/Python6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
minha_array = np.array([1, 2, 3, 4, 5, 6])
print(minha_array, type(minha_array))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [ ]:
minha_array.shape

(6,)

In [ ]:
minha_array.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
minha_array.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean

<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)>

In [ ]:
def media_geometrica(array_np):
    '''Array flat do numpy (uma unica dimensão).
    '''
    return np.prod(array_np)**(1/array_np.size)

media_geometrica(minha_array)

2.993795165523909

In [ ]:
def media_harmonica(array_np):
    '''array_np: array flat do numpy (uma unica dimensão).
    '''
    return 1/(np.mean(1/array_np))

media_harmonica(minha_array)

2.448979591836735

In [ ]:
def media_ponderada(array_amostras, array_pesos):
    '''entradas sao arrays flattened (uma unica dimensao no shape)
    '''
    return (array_amostras * array_pesos).sum() / array_pesos.sum()

In [ ]:
lucro_unitario = np.array([10., 1., 2.])
volume_de_vendas = np.array([100, 5000, 500])

media_ponderada(lucro_unitario, volume_de_vendas)


1.25

In [ ]:
np.array([10, 5]) * np.array([-1, 0.1]) 

NameError: ignored

In [ ]:
precos_lojas = dict({'Loja_A': 1000.0,
              'Loja_B': 1100.0,
               'Loja_C': 950.0,
               'Loja_D': 1250.0,
               'Loja_E': 10000.0,})
precos_lojas

{'Loja_A': 1000.0,
 'Loja_B': 1100.0,
 'Loja_C': 950.0,
 'Loja_D': 1250.0,
 'Loja_E': 10000.0}

In [ ]:
np.array(list(precos_lojas.values())).mean()

2860.0

In [ ]:
precos = np.array(list(precos_lojas.values()))
precos

array([ 1000.,  1100.,   950.,  1250., 10000.])

In [ ]:
def mediana_array_numpy(arr):
    '''arr: entrada flatened
    '''
    arr = np.sort(arr)

    arr_len = arr.size

    centro = (arr_len - 1) / 2

    if centro % 1 == 0:
        mediana = arr[int(centro)]
    else: 
        mediana = arr[int(np.floor(centro)):int(np.floor(centro) + 2)].mean()

    return mediana

    

In [ ]:
np.sort(precos)

array([  950.,  1000.,  1100.,  1250., 10000.])

In [ ]:
arr_precos = np.array([950.0, 1000.0, 1100.0, 1250.0, 10000.0, 1200.])

In [ ]:
np.sort(precos)

array([  950.,  1000.,  1100.,  1250., 10000.])

In [ ]:
mediana_array_numpy(arr_precos)

1150.0

In [ ]:
import pandas as pd

In [ ]:
pd.Series(arr_precos) # .median()

0      950.0
1     1000.0
2     1100.0
3     1250.0
4    10000.0
5     1200.0
dtype: float64

In [ ]:
from numpy.lib.function_base import median
arr = np.random.randint(1, 100, 7)
print(np.sort(arr))
(mediana_array_numpy(arr),
pd.Series(arr).median()
)

[27 50 74 77 78 87 96]


(77, 77.0)