<a href="https://colab.research.google.com/github/123franklin321/meu_primeiro_codigo.py/blob/master/Vari%C3%A2ncia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
x.mean()

3.5

In [5]:
desvios_da_media = x - x.mean()
print(desvios_da_media)

[-2.5 -1.5 -0.5  0.5  1.5  2.5]


In [6]:
desvios_da_media.mean()

0.0

In [8]:
variancia = (desvios_da_media**2).mean()
variancia

2.9166666666666665

In [9]:
(x**2).mean() - (x.mean())**2

2.916666666666666

In [10]:
desvio_padrao = np.sqrt(variancia)
desvio_padrao

1.707825127659933

In [12]:
x.mean() + np.array([-desvio_padrao, desvio_padrao])

array([1.79217487, 5.20782513])

In [13]:
x.mean() + np.array([-2*desvio_padrao, 2*desvio_padrao])

array([0.08434974, 6.91565026])

In [14]:
x_series = pd.Series(x)
x_series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [15]:
x.var()

2.9166666666666665

In [16]:
x.std()

1.707825127659933